; Bazaru de Gozaru - shop dialogue text alphabet values
; -----------------------------------------------------

; uppercase alphabet
;
cA	= $01
cB	= $02
cC	= $03
cD	= $04
cE	= $05
cF	= $06
cG	= $07
cH	= $08
cI	= $09
cJ	= $0A
cK	= $0B
cL	= $0C
cM	= $0D
cN	= $0E
cO	= $0F
cP	= $20
cQ	= $21
cR	= $22
cS	= $23
cT	= $24
cU	= $25
cV	= $26
cW	= $27
cX	= $28
cY	= $29
cZ	= $2A

; lowercase alphabet
;
lA	= $61
lB	= $62
lC	= $63
lD	= $64
lE	= $65
lF	= $66
lG	= $67
lH	= $68
lI	= $69
lJ	= $6A
lK	= $6B
lL	= $6C
lM	= $6D
lN	= $6E
lO	= $6F
lP	= $80
lQ	= $81
lR	= $82
lS	= $83
lT	= $84
lU	= $85
lV	= $86
lW	= $87
lX	= $88
lY	= $89
lZ	= $8A

perid	= $2B
apost	= $2C
spc	= $4E
dash	= $8B
qust	= $8E
excl	= $8F
